# Generated by Django 5.1.3 on 2024-11-18 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name of the langeuage of the book', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='languege',
            field=models.ForeignKey(default='english', on_delete=django.db.models.deletion.CASCADE, to='catalogues.languege'),
        ),
    ]
