# Generated by Django 5.1.3 on 2024-11-18 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_languege_book_languege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='languege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.languege'),
        ),
    ]
